### ISSUE TITLE
Better Documentation Design

### ISSUE THREAD

**Issue by EmadMokhtar** [Quran-Tafseer/tafseer_api#31]
The initial design is built with simple HTML  using bootstrap and [Flat-UI](http://designmodo.github.io/Flat-UI/) theme, we want to have better design docs.

**Comment by EmadMokhtar** [comment]
Look into Swagger docs.

**Comment by amerghazal** [comment]
if the API is [re]written in OAS/swaggerspec, you'll get a lot for free with swaggerui+generated clients - including better documentation. i've done this before, let me know if you'd like some assistance.

jazakumallahu khair on your work with this project

**Comment by EmadMokhtar** [comment]
@amerghazal I want to look into https://www.django-rest-framework.org/topics/documenting-your-api/ and pick the right package, if you like to contribute and help, you can do the research and implement it.

**Comment by amerghazal** [comment]
i'll take a stab at this in the coming few days, iA
